### ISSUE TITLE
A Note About Datasets in the ../pre Directory, and How to Disable Expanders Which Require Missing Datasets

### ISSUE THREAD

**Issue by kpoots** [hosseinfani/ReQue#5] opened 2020-09-04 17:02 UTC
This comment arose from Sep 3 testing of ReQue.

Not all query expanders were used, as my test version doesn't have all of the needed external datasets.

My version contains only the following datasets in the ../pre directory:
  anchor_text_en.ttl  gitkeep  glove.6B.300d.txt  wiki-news-300d-1M.vec 

To disable expanders which require files that are not yet available, in file ReQue/qe/cmn/expander_factory.py, the following lines were commented-out:

  in function get_nrf_expanders, these lines appear twice- comment out both copies:

                  Anchor(anchorfile='../pre/anchor_text_en.ttl', vectorfile='../pre/wiki-anchor-text-en   ttl-300d.vec'),
                  Wiki('../pre/temp_model_Wiki'),_
 
Commenting-out these lines seems to have lead to a complete run of the unsupervised query expanders. 
Results are being evaluated (please see #4 )

**Comment by hosseinfani** [comment] 2020-09-04 18:16
Duplicate of #1 but provides more help. So, I close this. 
We'll continue to address this issue at #1 and provide more help there.

**Closed as completed by hosseinfani** 2020-09-04 18:16 UTC
Labels: duplicate, help wanted, question
